# Kong API Gateway Secrets Configuration
# Version: 1.0.0
# Enhanced security with AWS KMS encryption and automated rotation
apiVersion: v1
kind: Secret
metadata:
  name: kong-gateway-secrets
  namespace: gameday-platform
  labels:
    app: kong-gateway
    component: api-gateway
    security-tier: critical
    encryption: aws-kms
  annotations:
    # AWS Secrets Manager integration
    secret.kubernetes.io/managed-by: aws-secrets-manager
    secret.kubernetes.io/last-rotation: "2024-01-15T00:00:00Z"
    secret.kubernetes.io/next-rotation: "2024-04-15T00:00:00Z"
    # AWS KMS encryption configuration
    encryption.aws.com/kms-key: "arn:aws:kms:${AWS_REGION}:${AWS_ACCOUNT_ID}:key/${KMS_KEY_ID}"
    # Automated backup configuration
    backup.kubernetes.io/deltas: "30"
    # Security context
    security.alpha.kubernetes.io/enforced: "true"
    # Audit logging
    audit.kubernetes.io/log-level: "RequestResponse"

type: Opaque

# Sensitive data encrypted with AWS KMS
data:
  # TLS certificate for HTTPS termination (90-day rotation)
  ssl_cert: "${BASE64_ENCODED_TLS_CERTIFICATE}"
  ssl_key: "${BASE64_ENCODED_PRIVATE_KEY}"
  
  # Kong Admin API authentication token (30-day rotation)
  admin_token: "${BASE64_ENCODED_32BYTE_TOKEN}"
  
  # JWT signing keys for API authentication (180-day rotation)
  jwt_secret: "${BASE64_ENCODED_RSA4096_KEY}"
  jwt_public_key: "${BASE64_ENCODED_RSA4096_PUBLIC_KEY}"
  
  # Session encryption key (30-day rotation)
  session_secret: "${BASE64_ENCODED_64BYTE_SECRET}"
  
  # OAuth/SAML configuration secrets
  oauth_client_secret: "${BASE64_ENCODED_OAUTH_SECRET}"
  saml_private_key: "${BASE64_ENCODED_SAML_KEY}"
  
  # Redis authentication for rate limiting
  redis_password: "${BASE64_ENCODED_REDIS_PASSWORD}"
  
  # Additional security configurations
  cors_allowed_origins: "${BASE64_ENCODED_CORS_ORIGINS}"
  rate_limiting_config: "${BASE64_ENCODED_RATE_LIMITS}"

stringData:
  # Security policy configuration
  security-policy.json: |
    {
      "encryption": {
        "algorithm": "AES-256-GCM",
        "key_rotation": "180d",
        "kms_key_id": "${KMS_KEY_ID}"
      },
      "access_control": {
        "rbac_enabled": true,
        "namespace_isolation": true,
        "pod_security": {
          "runAsNonRoot": true,
          "readOnlyRootFilesystem": true
        }
      },
      "monitoring": {
        "secret_rotation_alerts": true,
        "expiration_monitoring": true,
        "audit_logging": {
          "enabled": true,
          "retention": "1y"
        }
      }
    }