apiVersion: v1
kind: Service
metadata:
  name: kong-gateway
  namespace: gameday-platform
  labels:
    app: kong-gateway
    component: api-gateway
    part-of: gameday-platform
    managed-by: kubernetes
  annotations:
    # AWS Load Balancer Configuration
    service.beta.kubernetes.io/aws-load-balancer-type: "application"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "${SSL_CERT_ARN}"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443,8444"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    
    # Health Check Configuration
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "HTTP"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/health"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "8000"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "30"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "5"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "2"
    
    # Prometheus Monitoring
    prometheus.io/scrape: "true"
    prometheus.io/port: "8001"
    prometheus.io/path: "/metrics"

spec:
  type: LoadBalancer
  ports:
    # HTTP proxy port
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
    
    # HTTPS proxy port
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
    
    # Admin API port
    - name: admin
      port: 8001
      targetPort: 8001
      protocol: TCP
    
    # Admin SSL port
    - name: admin-ssl
      port: 8444
      targetPort: 8444
      protocol: TCP
  
  # Pod selector matching Kong Gateway deployment
  selector:
    app: kong-gateway
  
  # Session handling and traffic policy
  sessionAffinity: None
  externalTrafficPolicy: Local