# PersistentVolumeClaim configurations for GameDay Platform data stores
# Provides encrypted, performance-optimized storage for MongoDB, InfluxDB and Redis
# Version: 1.0
# Last Updated: 2024-01

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data-pvc
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.amazon.com
    volume.kubernetes.io/selected-node: ""  # Dynamically set by scheduler
    backup.velero.io/backup-volumes: mongodb-data  # Enable Velero backups
spec:
  accessModes:
    - ReadWriteOnce  # Single node access for data consistency
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi  # Production-grade storage for document store
  storageClassName: gameday-io-optimized  # High IOPS storage class
  selector:
    matchLabels:
      type: mongodb-storage
      encryption: enabled
      performance-tier: io-optimized

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-data-pvc
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.amazon.com
    volume.kubernetes.io/selected-node: ""  # Dynamically set by scheduler
    backup.velero.io/backup-volumes: influxdb-data  # Enable Velero backups
spec:
  accessModes:
    - ReadWriteOnce  # Single node access for time series data
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi  # Optimized for time series data storage
  storageClassName: gameday-io-optimized  # High IOPS storage class
  selector:
    matchLabels:
      type: influxdb-storage
      encryption: enabled
      performance-tier: io-optimized

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-pvc
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.amazon.com
    volume.kubernetes.io/selected-node: ""  # Dynamically set by scheduler
    backup.velero.io/backup-volumes: redis-data  # Enable Velero backups
spec:
  accessModes:
    - ReadWriteOnce  # Single node access for cache data
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi  # Sufficient for cache data storage
  storageClassName: gameday-gp3-storage  # Cost-effective general purpose storage
  selector:
    matchLabels:
      type: redis-storage
      encryption: enabled
      performance-tier: standard