apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secrets
  namespace: gameday-platform
  labels:
    app: notification-service
    component: secrets
    environment: production
    managed-by: terraform
    rotation-schedule: 30-days
  annotations:
    encryption.gameday.io/version: "v1"
    encryption.gameday.io/algorithm: "AES-256-GCM"
    secret.gameday.io/last-rotated: "2024-01-15T00:00:00Z"  # Set to current deployment timestamp
    secret.gameday.io/next-rotation: "2024-02-14T00:00:00Z" # Set to current timestamp + 30 days
type: Opaque
data:
  # MongoDB Credentials
  # Rotation: 30 days, Encoding: base64
  # Used by: database.ts for MongoDB authentication
  MONGODB_USERNAME: "bm90aWZpY2F0aW9uLXNlcnZpY2UtdXNlcg=="  # notification-service-user
  MONGODB_PASSWORD: "WW91clN0cm9uZ1Bhc3N3b3JkSGVyZQ=="      # Base64 encoded strong password

  # Redis Message Queue Authentication
  # Rotation: 30 days, Encoding: base64
  # Used by: queue.ts for async operations
  REDIS_PASSWORD: "UmVkaXNTdHJvbmdQYXNzd29yZA=="            # Base64 encoded Redis password

  # Slack Integration Credentials
  # Rotation: 30 days, Encoding: base64
  # Used by: slack.adapter.ts for workspace integration
  SLACK_API_TOKEN: "eG94Yi1zbGFjay10b2tlbi1oZXJl"           # Base64 encoded Slack Bot User OAuth Token

  # Microsoft Teams Integration Credentials
  # Rotation: 30 days, Encoding: base64
  # Used by: teams.adapter.ts for tenant integration
  TEAMS_CLIENT_ID: "dGVhbXMtY2xpZW50LWlkLWhlcmU="           # Base64 encoded Teams Client ID
  TEAMS_CLIENT_SECRET: "dGVhbXMtY2xpZW50LXNlY3JldC1oZXJl"   # Base64 encoded Teams Client Secret

---
# RBAC Configuration for Secret Access
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: notification-service-secrets-reader
  namespace: gameday-platform
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["notification-service-secrets"]
  verbs: ["get", "list"]

---
# Role Binding for Service Account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: notification-service-secrets-reader-binding
  namespace: gameday-platform
subjects:
- kind: ServiceAccount
  name: notification-service-sa
  namespace: gameday-platform
roleRef:
  kind: Role
  name: notification-service-secrets-reader
  apiGroup: rbac.authorization.k8s.io