apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-service-config
  namespace: gameday-platform
  labels:
    app: analytics-service
    component: backend
    part-of: gameday-platform
    managed-by: kubectl
    version: v1.0.0
  annotations:
    description: "Analytics Service configuration settings"
    lastUpdated: "2024-01-30"

data:
  # Service Configuration
  SERVICE_NAME: "analytics-service"
  SERVICE_PORT: "8000"
  SERVICE_VERSION: "1.0.0"
  ENVIRONMENT: "production"
  CORRELATION_ID_HEADER: "X-Correlation-ID"

  # Logging Configuration
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  LOG_FILE_MAX_SIZE: "100"  # MB
  LOG_FILE_MAX_FILES: "5"
  LOG_SANITIZE_FIELDS: "password,token,secret,key"
  LOG_JSON_OUTPUT: "true"

  # MongoDB Configuration (non-sensitive)
  MONGODB_HOST: "mongodb-service"
  MONGODB_PORT: "27017"
  MONGODB_DATABASE: "gameday_analytics"
  MONGODB_OPTIONS: '{"maxPoolSize": 50, "connectTimeoutMS": 5000, "maxIdleTimeMS": 30000}'
  MONGODB_SSL_ENABLED: "true"

  # InfluxDB Configuration (non-sensitive)
  INFLUXDB_HOST: "influxdb-service"
  INFLUXDB_PORT: "8086"
  INFLUXDB_ORG: "gameday"
  INFLUXDB_BUCKET: "metrics"
  METRICS_RETENTION_DAYS: "90"
  METRICS_BATCH_SIZE: "1000"
  METRICS_FLUSH_INTERVAL: "10"

  # Performance Configuration
  POOL_SIZE: "50"
  MAX_CONNECTIONS: "100"
  TIMEOUT_MS: "5000"

  # Security Headers
  SECURITY_HEADERS: |
    {
      "X-Content-Type-Options": "nosniff",
      "X-Frame-Options": "DENY",
      "X-XSS-Protection": "1; mode=block",
      "Strict-Transport-Security": "max-age=31536000; includeSubDomains"
    }

  # Feature Flags
  FEATURE_FLAGS: |
    {
      "enableEnhancedAnalytics": true,
      "enableRealTimeMetrics": true,
      "enableHistoricalTrends": true
    }