apiVersion: v1
kind: Secret
metadata:
  name: analytics-service-secrets
  namespace: gameday-platform
  labels:
    app: analytics-service
    component: backend
    part-of: gameday-platform
    managed-by: platform-team
    environment: production
  annotations:
    # Secret rotation metadata
    rotation.gameday.io/last-rotated: "2024-01-15T00:00:00Z"
    rotation.gameday.io/next-rotation: "2024-02-14T00:00:00Z"
    # Security controls
    security.gameday.io/encryption: "aes256-gcm"
    security.gameday.io/compliance: "soc2,gdpr,hipaa"
    # Audit and backup configurations
    audit.gameday.io/enabled: "true"
    audit.gameday.io/retention: "365d"
    backup.gameday.io/included: "true"
    backup.gameday.io/schedule: "daily"
    # Documentation
    description: "Analytics Service credentials and configuration secrets"
    owner: "platform-team"
type: Opaque
data:
  # Database Credentials - 90 day rotation
  MONGODB_USERNAME: ${BASE64_ENCODED_MONGODB_USERNAME}
  MONGODB_PASSWORD: ${BASE64_ENCODED_MONGODB_PASSWORD}
  MONGODB_CONNECTION_STRING: ${BASE64_ENCODED_MONGODB_CONNECTION_STRING}
  
  # Metrics Store Credentials - 30 day rotation
  INFLUXDB_TOKEN: ${BASE64_ENCODED_INFLUXDB_TOKEN}
  INFLUXDB_API_KEY: ${BASE64_ENCODED_INFLUXDB_API_KEY}
  INFLUXDB_ORG_TOKEN: ${BASE64_ENCODED_INFLUXDB_ORG_TOKEN}
  METRICS_API_KEY: ${BASE64_ENCODED_METRICS_API_KEY}
  
  # Service Authentication - 30 day rotation
  SERVICE_API_KEY: ${BASE64_ENCODED_SERVICE_API_KEY}
  JWT_SECRET_KEY: ${BASE64_ENCODED_JWT_SECRET_KEY}
  JWT_REFRESH_KEY: ${BASE64_ENCODED_JWT_REFRESH_KEY}
  
  # Data Protection - 180 day rotation
  ENCRYPTION_KEY: ${BASE64_ENCODED_ENCRYPTION_KEY}
  ENCRYPTION_SALT: ${BASE64_ENCODED_ENCRYPTION_SALT}

---
# Immutable ConfigMap for non-sensitive metadata
apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-service-secret-metadata
  namespace: gameday-platform
  labels:
    app: analytics-service
    component: backend
data:
  rotation-policy.json: |
    {
      "database_credentials": "90d",
      "api_keys": "30d",
      "encryption_keys": "180d",
      "jwt_secrets": "30d",
      "emergency_contacts": [
        "security-team@gameday.io",
        "platform-team@gameday.io"
      ]
    }
  access-policy.json: |
    {
      "allowed_services": [
        "analytics-service",
        "exercise-service"
      ],
      "allowed_roles": [
        "system-admin",
        "security-operator"
      ],
      "audit_retention": "365d",
      "alert_threshold": "5"
    }