# ServiceAccount definition for GameDay Platform services
# Version: v1
# Purpose: Provides identity and access management within the Kubernetes cluster
# with enhanced security controls and cloud provider IAM integration

apiVersion: v1
kind: ServiceAccount
metadata:
  name: gameday-platform-sa
  namespace: gameday-platform
  labels:
    app: gameday-platform
    component: rbac
    environment: ${ENV}
    managed-by: terraform
    security-tier: restricted
  annotations:
    # AWS IAM role integration for EKS
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/gameday-platform-role
    eks.amazonaws.com/sts-regional-endpoints: "true"
    eks.amazonaws.com/token-expiration: "3600"
    
    # Security controls
    kubernetes.io/enforce-mountable-secrets: "true"
    
    # GCP Workload Identity integration (for multi-cloud support)
    security.cloud.google.com/use-workload-identity: "true"
    iam.gke.io/gcp-service-account: gameday-platform@${PROJECT_ID}.iam.gserviceaccount.com

# Enable automatic token mounting for pod authentication
automountServiceAccountToken: true

# Container registry credentials
imagePullSecrets:
  - name: gameday-platform-registry