apiVersion: v1
kind: Secret
metadata:
  name: exercise-service-secrets
  namespace: gameday
  labels:
    app: exercise-service
    component: backend
    part-of: gameday-platform
    managed-by: terraform
    environment: ${ENV}
    version: ${VERSION}
  annotations:
    kubernetes.io/created-by: terraform
    # Enable automatic secret rotation every 30 days
    secret.kubernetes.io/auto-rotation: "enabled"
    secret.kubernetes.io/rotation-period: "30d"
    # Enable Vault integration for enhanced secret management
    vault.hashicorp.com/agent-inject: "true"

type: Opaque

data:
  # MongoDB Credentials
  MONGODB_USERNAME: ${base64encode(mongodb_username)}
  MONGODB_PASSWORD: ${base64encode(mongodb_password)}
  MONGODB_DATABASE: ${base64encode(mongodb_database)}
  MONGODB_AUTH_SOURCE: ${base64encode(mongodb_auth_source)}
  MONGODB_REPLICA_SET: ${base64encode(mongodb_replica_set)}

  # Redis Credentials
  REDIS_USERNAME: ${base64encode(redis_username)}
  REDIS_PASSWORD: ${base64encode(redis_password)}
  REDIS_TLS_CA: ${base64encode(redis_tls_ca)}

  # JWT Configuration
  JWT_SECRET: ${base64encode(jwt_secret)}
  JWT_PRIVATE_KEY: ${base64encode(jwt_private_key)}
  JWT_PUBLIC_KEY: ${base64encode(jwt_public_key)}
  JWT_EXPIRATION: ${base64encode(jwt_expiration)}

  # Encryption Keys
  ENCRYPTION_KEY: ${base64encode(encryption_key)}
  ENCRYPTION_IV: ${base64encode(encryption_iv)}
  AUDIT_ENCRYPTION_KEY: ${base64encode(audit_encryption_key)}

  # API Authentication
  API_KEY: ${base64encode(api_key)}
  API_SECRET: ${base64encode(api_secret)}
  
  # External Service Keys
  LLM_API_KEY: ${base64encode(llm_api_key)}