apiVersion: v1
kind: Service
metadata:
  name: exercise-service
  namespace: gameday
  labels:
    app: exercise-service
    component: backend
    part-of: gameday-platform
    version: v1
    istio-injection: enabled
  annotations:
    # Prometheus monitoring configuration
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
    # Istio service mesh configuration
    service.istio.io/canonical-name: "exercise-service"
    service.istio.io/canonical-revision: "v1"
spec:
  # Using ClusterIP for internal cluster access
  type: ClusterIP
  ports:
    # Main application port
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    # Metrics port for monitoring
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: metrics
  # Pod selector for service targeting
  selector:
    app: exercise-service
    component: backend
  # Session handling configuration
  sessionAffinity: None
  # Pod readiness configuration
  publishNotReadyAddresses: false