# Secret resource for GameDay Platform web frontend
# Version: v1
# Managed by: External Secrets Operator
# Encryption: AWS KMS with AES-256-GCM
# Rotation: 180 days

apiVersion: v1
kind: Secret
metadata:
  name: web-secrets
  namespace: gameday-platform
  labels:
    app: gameday-web
    component: frontend
    environment: production
    managed-by: terraform
    encryption: aws-kms
  annotations:
    # Enable automatic reloading when secret changes
    reloader.stakater.com/match: "true"
    # Managed by External Secrets Operator
    secret.kubernetes.io/managed-by: external-secrets-operator
    # AWS KMS encryption key reference
    eks.amazonaws.com/kms-key-id: ${KMS_KEY_ARN}
    # Automatic rotation after 180 days
    kubernetes.io/rotate-after: "180d"
type: Opaque
data:
  # Auth0 client secret for authentication
  VITE_AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
  # API key for backend service communication
  VITE_API_KEY: ${API_KEY}
  # JWT signing secret for token validation
  VITE_JWT_SECRET: ${JWT_SECRET}
  # Encryption key for client-side data protection
  VITE_ENCRYPTION_KEY: ${ENCRYPTION_KEY}

---
# Network Policy to restrict secret access
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: web-secrets-policy
  namespace: gameday-platform
spec:
  podSelector:
    matchLabels:
      app: gameday-web
      component: frontend
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: gameday-web
              component: frontend
  egress: []

---
# RBAC configuration for secret access
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: web-secrets-reader
  namespace: gameday-platform
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["web-secrets"]
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web-secrets-reader-binding
  namespace: gameday-platform
subjects:
  - kind: ServiceAccount
    name: web-service-account
    namespace: gameday-platform
roleRef:
  kind: Role
  name: web-secrets-reader
  apiGroup: rbac.authorization.k8s.io