apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: gameday-platform
  labels:
    app: gameday-web
    component: frontend
    environment: production
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: gameday-web